(() => {
  const $=s=>document.querySelector(s);let token=sessionStorage.getItem('leedsRadarAdminToken')||'';
  $('#adminToken').value=token;bind();loadBoard();
  function bind(){
    $('#saveToken').addEventListener('click',()=>{token=$('#adminToken').value.trim();sessionStorage.setItem('leedsRadarAdminToken',token);status(token?'Token ready for this tab.':'Token removed.',Boolean(token))});
    $('#reloadBoard').addEventListener('click',loadBoard);
    $('#forceRefresh').addEventListener('click',async()=>{const button=$('#forceRefresh');button.disabled=true;try{const data=await adminPost('/api/transfers/admin/refresh',{});$('#refreshResult').textContent=JSON.stringify(data,null,2);await loadBoard()}catch(error){$('#refreshResult').textContent=error.message}finally{button.disabled=false}});
    $('#overrideForm').addEventListener('submit',async event=>{event.preventDefault();const form=new FormData(event.currentTarget);const payload={playerName:form.get('playerName'),direction:form.get('direction'),stage:Number(form.get('stage')),note:form.get('note'),hidden:form.get('hidden')==='on'};await submit(event.currentTarget,'/api/transfers/admin/override',payload)});
    $('#sourceForm').addEventListener('submit',async event=>{event.preventDefault();const form=new FormData(event.currentTarget);const payload={handle:form.get('handle'),displayName:form.get('displayName'),tier:form.get('tier'),weight:Number(form.get('weight')),official:form.get('official')==='on',enabled:form.get('enabled')==='on'};await submit(event.currentTarget,'/api/transfers/admin/source',payload)});
  }
  async function submit(form,url,payload){const button=form.querySelector('button[type=submit]');button.disabled=true;try{await adminPost(url,payload);status('Saved successfully.',true);await loadBoard()}catch(error){status(error.message,false)}finally{button.disabled=false}}
  async function adminPost(url,payload){token=$('#adminToken').value.trim()||token;if(!token)throw new Error('Paste the BIZBOT_ADMIN_TOKEN first.');const response=await fetch(url,{method:'POST',headers:{authorization:`Bearer ${token}`,'content-type':'application/json'},body:JSON.stringify(payload)});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(data.error||`Request failed (${response.status})`);return data}
  async function loadBoard(){try{token=$('#adminToken').value.trim()||token;if(!token){status('Enter the BIZBOT_ADMIN_TOKEN to load private source controls.',false);return;}const [boardRes,completedRes]=await Promise.all([fetch('/api/transfers/admin/board',{headers:{authorization:`Bearer ${token}`},cache:'no-store'}),fetch('/api/transfers/radar?completed=1',{cache:'no-store'})]);const active=await boardRes.json(),completed=await completedRes.json();if(!boardRes.ok||!active.ok)throw new Error(active.error||'Radar unavailable');renderTargets([...(active.targets||[]),...(completed.targets||[])]);renderSources(active.sources||[]);const auto=active.automation||{};status(auto.mode==='automatic'?`Automatic feed active · last success ${auto.lastSuccessfulRefreshAt||'pending'}`:'Radar installed · X token not connected yet',auto.mode==='automatic')}catch(error){status(error.message,false)}}
  function renderTargets(rows){$('#targetBoard').innerHTML=rows.length?rows.map(row=>`<div class="board-row"><div><b>${esc(row.playerName)}</b><small>${esc(row.direction)} · ${esc(row.stageLabel)}</small></div><strong>${Number(row.confidence||0)}</strong></div>`).join(''):'No targets yet.'}
  function renderSources(rows){$('#sourceBoardAdmin').innerHTML=rows.length?rows.map(row=>`<div class="board-row"><div><b>${esc(row.display_name)}</b><small>@${esc(row.handle)} · ${esc(row.tier)}</small></div><strong>${Number(row.weight||0)}</strong></div>`).join(''):'No sources loaded.'}
  function status(message,live){const el=$('#adminStatus');el.textContent=message;el.classList.toggle('live',Boolean(live))}
  function esc(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
})();
