import { BLUE_VAULT_DATABASE } from './data/blue-vault-database.js?v=18.0.0';
import { CURRENT_PLAYER_METADATA } from './data/current-player-metadata.js?v=18.0.0';
import { BLUE_DNA_OVERRIDES } from './data/blue-dna-ratings.js?v=18.0.0';

const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const STORE='leedsbuzz-biz-xi-saves-v19', DRAFT='leedsbuzz-biz-xi-draft-v20', OLD_DRAFT='leedsbuzz-biz-xi-draft-v19';
const OUTFIELD=['PACE','SHOOTING','PASSING','DRIBBLING','DEFENDING','PHYSICAL'];
const GK=['SHOT STOPPING','HANDLING','COMMAND','DISTRIBUTION','1 V 1','SWEEPING'];
const WEIGHTS={GK:[.27,.17,.18,.14,.14,.10],CB:[.08,.04,.14,.06,.40,.28],FB:[.18,.05,.17,.15,.28,.17],DM:[.10,.07,.23,.13,.27,.20],CM:[.12,.14,.26,.20,.13,.15],AM:[.14,.22,.22,.25,.05,.12],WINGER:[.23,.22,.17,.25,.03,.10],ST:[.17,.32,.11,.18,.04,.18],LBUZZ:[.16,.16,.18,.18,.16,.16]};
const BASE={GK:[72,70,70,66,72,62],CB:[62,38,65,53,80,80],FB:[75,48,69,68,74,72],DM:[66,53,76,68,79,77],CM:[69,66,79,76,66,72],AM:[74,77,82,84,48,67],WINGER:[83,75,73,85,43,66],ST:[76,83,64,74,38,79],LBUZZ:[68,64,70,69,64,71]};
const FORMATIONS={
 '4-3-3':[['GK',50,91],['LB',17,73],['LCB',39,78],['RCB',61,78],['RB',83,73],['LCM',28,52],['CM',50,57],['RCM',72,52],['LW',19,27],['ST',50,17],['RW',81,27]],
 '4-2-3-1':[['GK',50,91],['LB',17,74],['LCB',39,79],['RCB',61,79],['RB',83,74],['LDM',35,59],['RDM',65,59],['LW',18,38],['CAM',50,40],['RW',82,38],['ST',50,17]],
 '4-4-2':[['GK',50,91],['LB',17,74],['LCB',39,79],['RCB',61,79],['RB',83,74],['LM',17,48],['LCM',40,55],['RCM',60,55],['RM',83,48],['LST',38,20],['RST',62,20]],
 '3-4-3':[['GK',50,91],['LCB',25,76],['CB',50,80],['RCB',75,76],['LM',16,51],['LCM',39,56],['RCM',61,56],['RM',84,51],['LW',20,27],['ST',50,17],['RW',80,27]],
 '3-5-2':[['GK',50,91],['LCB',25,76],['CB',50,80],['RCB',75,76],['LWB',15,53],['LCM',35,55],['CAM',50,42],['RCM',65,55],['RWB',85,53],['LST',38,20],['RST',62,20]],
 '5-3-2':[['GK',50,91],['LWB',11,65],['LCB',29,77],['CB',50,81],['RCB',71,77],['RWB',89,65],['LCM',31,49],['CM',50,55],['RCM',69,49],['LST',38,20],['RST',62,20]]
};
const TACTICS={
 balanced:{name:'Balanced',description:'Balanced structure with quality in every phase.',out:[.16,.17,.18,.17,.16,.16],gk:[.24,.18,.19,.16,.13,.10]},
 possession:{name:'Possession',description:'Control the ball through passing, technique and calm build-up.',out:[.07,.08,.32,.27,.10,.16],gk:[.14,.14,.17,.31,.08,.16]},
 counter:{name:'Counter Attack',description:'Explode forward with pace, direct passing and ruthless finishing.',out:[.29,.26,.15,.19,.03,.08],gk:[.17,.10,.18,.29,.12,.14]},
 highPress:{name:'High Press',description:'Win the ball high through speed, defending and physical intensity.',out:[.18,.10,.12,.10,.25,.25],gk:[.16,.13,.18,.20,.12,.21]},
 lowBlock:{name:'Low Block',description:'Protect the box with defensive strength, command and discipline.',out:[.05,.04,.12,.07,.41,.31],gk:[.31,.22,.24,.10,.09,.04]},
 wingPlay:{name:'Wing Play',description:'Stretch the pitch with pace, dribbling and delivery from wide areas.',out:[.27,.13,.25,.25,.04,.06],gk:[.16,.13,.18,.28,.10,.15]}
};
const POSITION_FIT={
 GK:{GK:100,CB:3,FB:3,DM:3,CM:3,AM:3,WINGER:3,ST:3,LBUZZ:6},
 CB:{CB:100,FB:74,DM:76,CM:48,AM:24,WINGER:16,ST:12,GK:3,LBUZZ:50},
 FB:{FB:100,WINGER:72,CB:66,DM:62,CM:48,AM:38,ST:24,GK:3,LBUZZ:52},
 WB:{FB:96,WINGER:89,CM:64,DM:61,AM:57,CB:55,ST:32,GK:3,LBUZZ:52},
 DM:{DM:100,CM:87,CB:80,FB:68,AM:58,WINGER:41,ST:25,GK:3,LBUZZ:53},
 CM:{CM:100,AM:87,DM:85,WINGER:68,FB:56,CB:51,ST:48,GK:3,LBUZZ:55},
 AM:{AM:100,WINGER:87,CM:84,ST:72,DM:53,FB:44,CB:29,GK:3,LBUZZ:55},
 WM:{WINGER:97,AM:84,FB:80,CM:73,ST:62,DM:54,CB:36,GK:3,LBUZZ:54},
 WINGER:{WINGER:100,AM:84,ST:80,FB:64,CM:55,DM:36,CB:22,GK:3,LBUZZ:54},
 ST:{ST:100,WINGER:79,AM:67,CM:38,DM:23,FB:19,CB:15,GK:3,LBUZZ:50}
};
let players=[], bySlug=new Map(), state={title:'My Ultimate Leeds XI',formation:'4-3-3',tactic:'balanced',slots:[],subs:[],captain:'',viceCaptain:'',updatedAt:new Date().toISOString()}, pickerTarget=null, previewSlug=null, member=null;
const slugify=v=>String(v||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/&/g,' and ').replace(/[’']/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const initials=name=>String(name||'LBUZZ').split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase();
const clamp=(n,a=35,b=99)=>Math.max(a,Math.min(b,Math.round(Number(n)||0)));
function inferRole(p){const o=BLUE_DNA_OVERRIDES[p.slug];if(o?.role)return o.role;const pos=String(p.position||CURRENT_PLAYER_METADATA[p.slug]?.position||'').toLowerCase();if(/goal/.test(pos))return'GK';if(/centre.?back|central defender/.test(pos))return'CB';if(/full.?back|wing.?back|defender/.test(pos))return'FB';if(/defensive|holding/.test(pos))return'DM';if(/attacking/.test(pos))return'AM';if(/wing/.test(pos))return'WINGER';if(/striker|forward/.test(pos))return'ST';if(/midfield/.test(pos))return'CM';return'LBUZZ'}
function roleGroup(role){if(role==='GK')return'GK';if(['CB','FB'].includes(role))return'DEF';if(['DM','CM','AM'].includes(role))return'MID';if(['WINGER','ST'].includes(role))return'FWD';return'ARCHIVE'}
function ratings(p){const role=inferRole(p), override=BLUE_DNA_OVERRIDES[p.slug];let scores=override?.scores?.slice()||BASE[role].slice();if(!override){const apps=Math.min(14,Math.log10(Math.max(10,Number(p.appearances)||10))*5);scores=scores.map((v,i)=>clamp(v+apps+(i===4&&['CB','FB','DM'].includes(role)?5:0)));}const w=WEIGHTS[role]||WEIGHTS.LBUZZ;return{role,scores,overall:clamp(scores.reduce((s,v,i)=>s+v*w[i],0)),impact:override?.impact||clamp(56+Math.log10(Math.max(1,Number(p.appearances)||1))*15),note:override?.note||'LeedsBuzz.biz archive-model rating.',labels:role==='GK'?GK:OUTFIELD}}
function buildPlayers(){const raw=BLUE_VAULT_DATABASE?.players||[];players=raw.map(r=>{const meta=CURRENT_PLAYER_METADATA[r.slug]||{};const p={...r,name:r.displayName||r.fullName,position:r.position||meta.position||'',nationality:r.nationality||meta.nationality||'',clubCareer:r.clubCareer||meta.clubCareer||'',shirtNumber:r.shirtNumber||meta.shirtNumber||'',slug:r.slug||slugify(r.fullName)};p.rating=ratings(p);p.role=p.rating.role;p.group=roleGroup(p.role);return p}).sort((a,b)=>(b.rating?.overall||0)-(a.rating?.overall||0)||(b.appearances||0)-(a.appearances||0));bySlug=new Map(players.map(p=>[p.slug,p]));}
function newState(formation='4-3-3',preserve=[],tactic=state.tactic||'balanced'){state={title:'My Ultimate Leeds XI',formation,tactic,slots:FORMATIONS[formation].map((s,i)=>({id:`slot-${i}`,label:s[0],x:s[1],y:s[2],slug:preserve[i]?.slug||''})),subs:[],captain:'',viceCaptain:'',updatedAt:new Date().toISOString()};}
function toast(text){const el=$('#xiToast');el.textContent=text;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2600)}
function slotGroup(label){if(label==='GK')return'GK';if(/B$|CB|WB/.test(label))return'DEF';if(/M|DM|CAM/.test(label))return'MID';return'FWD'}

const scoreClamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,Math.round(Number(n)||0)));
function slotRole(label){if(label==='GK')return'GK';if(/CB/.test(label))return'CB';if(/WB/.test(label))return'WB';if(/^(L|R)?B$/.test(label))return'FB';if(/DM/.test(label))return'DM';if(/CAM/.test(label))return'AM';if(/CM/.test(label))return'CM';if(/^(L|R)M$/.test(label))return'WM';if(/W$/.test(label))return'WINGER';if(/ST/.test(label))return'ST';return'CM'}
function positionFit(p,label){return POSITION_FIT[slotRole(label)]?.[p?.role]??45}
function fitTier(n){return n>=90?'elite':n>=72?'good':n>=45?'warning':'bad'}
function tacticalFit(p,tactic=state.tactic){if(!p)return 0;const cfg=TACTICS[tactic]||TACTICS.balanced,w=p.role==='GK'?cfg.gk:cfg.out,weighted=p.rating.scores.reduce((sum,v,i)=>sum+v*(w[i]||0),0);return scoreClamp(weighted*.72+p.rating.overall*.28,1,99)}
function candidateFit(p,label){return positionFit(p,label)*.68+tacticalFit(p)*.22+p.rating.overall*.10}
function traitSet(p){if(!p)return{pace:0,shoot:0,pass:0,dribble:0,defend:0,physical:0};const s=p.rating.scores;if(p.role==='GK')return{pace:s[5],shoot:8,pass:s[3],dribble:s[5],defend:(s[0]+s[1]+s[2])/3,physical:s[2]};return{pace:s[0],shoot:s[1],pass:s[2],dribble:s[3],defend:s[4],physical:s[5]}}
function positionalQuality(p,label){if(!p)return 0;const key=slotRole(label),t=traitSet(p);if(key==='GK')return p.role==='GK'?p.rating.overall:3;const weights={CB:[.10,.02,.14,.04,.42,.28],FB:[.23,.04,.20,.20,.20,.13],WB:[.27,.07,.22,.24,.10,.10],DM:[.09,.05,.29,.14,.28,.15],CM:[.10,.12,.30,.24,.11,.13],AM:[.12,.20,.28,.28,.03,.09],WM:[.24,.15,.24,.25,.04,.08],WINGER:[.28,.20,.19,.26,.02,.05],ST:[.16,.35,.10,.17,.03,.19]}[key]||[.16,.16,.18,.18,.16,.16],v=[t.pace,t.shoot,t.pass,t.dribble,t.defend,t.physical];return scoreClamp(v.reduce((a,n,i)=>a+n*weights[i],0),1,99)}
function expectedLinks(slots=state.slots){const found=new Map(),add=(i,j,d)=>{const a=Math.min(i,j),b=Math.max(i,j),k=`${a}-${b}`;if(!found.has(k)||found.get(k).distance>d)found.set(k,{a,b,distance:d})};slots.forEach((s,i)=>{const near=slots.map((t,j)=>({j,d:Math.hypot(s.x-t.x,s.y-t.y)})).filter(x=>x.j!==i).sort((a,b)=>a.d-b.d).slice(0,2);near.forEach(x=>add(i,x.j,x.d));});slots.forEach((s,i)=>slots.forEach((t,j)=>{if(j<=i)return;const dx=Math.abs(s.x-t.x),dy=Math.abs(s.y-t.y),d=Math.hypot(dx,dy);if(d<34&&(dy<9||dx<22))add(i,j,d)}));return [...found.values()].sort((a,b)=>a.distance-b.distance)}
function pairCompatibility(a,b,sa,sb){if(!a||!b)return 0;const ta=traitSet(a),tb=traitSet(b),ga=slotGroup(sa.label),gb=slotGroup(sb.label),fit=(positionFit(a,sa.label)+positionFit(b,sb.label))/2,tac=(tacticalFit(a)+tacticalFit(b))/2,quality=(a.rating.overall+b.rating.overall)/2;let football=quality;if(ga==='GK'||gb==='GK'){const g=ga==='GK'?a:b,o=ga==='GK'?b:a,gs=g.rating.scores,ot=traitSet(o);football=(gs[2]*.24+gs[3]*.22+gs[0]*.18+ot.defend*.22+ot.physical*.14)}else{const pair=[ga,gb].sort().join('-');if(pair==='DEF-DEF')football=(Math.max(ta.pass,tb.pass)*.18+Math.max(ta.pace,tb.pace)*.15+(ta.defend+tb.defend)/2*.38+(ta.physical+tb.physical)/2*.29);else if(pair==='DEF-MID')football=(Math.max(ta.defend,tb.defend)*.27+Math.max(ta.physical,tb.physical)*.18+Math.max(ta.pass,tb.pass)*.31+Math.max(ta.dribble,tb.dribble)*.14+Math.max(ta.pace,tb.pace)*.10);else if(pair==='DEF-FWD')football=((ta.defend+tb.defend)/2*.18+Math.max(ta.pass,tb.pass)*.22+Math.max(ta.pace,tb.pace)*.23+Math.max(ta.shoot,tb.shoot)*.22+Math.max(ta.physical,tb.physical)*.15);else if(pair==='MID-MID')football=(Math.max(ta.pass,tb.pass)*.29+Math.max(ta.dribble,tb.dribble)*.22+Math.max(ta.defend,tb.defend)*.20+Math.max(ta.shoot,tb.shoot)*.16+Math.max(ta.physical,tb.physical)*.13);else if(pair==='FWD-MID')football=(Math.max(ta.pass,tb.pass)*.27+Math.max(ta.dribble,tb.dribble)*.22+Math.max(ta.shoot,tb.shoot)*.29+Math.max(ta.pace,tb.pace)*.16+Math.max(ta.physical,tb.physical)*.06);else if(pair==='FWD-FWD')football=(Math.max(ta.shoot,tb.shoot)*.31+Math.max(ta.pass,tb.pass)*.20+Math.max(ta.dribble,tb.dribble)*.22+Math.max(ta.pace,tb.pace)*.19+Math.max(ta.physical,tb.physical)*.08)}return scoreClamp(fit*.28+tac*.22+football*.36+quality*.14,3,99)}
function chemistryRank(score,count){if(!count)return'BUILD YOUR XI';if(score<25)return'NO SHAPE YET';if(score<45)return'DISJOINTED XI';if(score<62)return'WORK IN PROGRESS';if(score<76)return'CONNECTED LEEDS FANS';if(score<88)return'TACTICAL UNIT';if(score<97)return'SUPER TEAM';if(score<100)return'ELITE LEEDS XI';return'ULTIMATE BLUE XI'}
function computeChemistry(){const selected=state.slots.map((slot,i)=>({slot,p:bySlug.get(slot.slug),i})),count=selected.filter(x=>x.p).length,position=selected.reduce((a,x)=>a+(x.p?positionFit(x.p,x.slot.label):0),0)/11,tactics=selected.reduce((a,x)=>a+(x.p?tacticalFit(x.p)*positionFit(x.p,x.slot.label)/100:0),0)/11,quality=selected.reduce((a,x)=>a+(x.p?positionalQuality(x.p,x.slot.label)*positionFit(x.p,x.slot.label)/100:0),0)/11,pairs=expectedLinks(),pairResults=pairs.map(link=>{const a=selected[link.a],b=selected[link.b];return{...link,score:a.p&&b.p?pairCompatibility(a.p,b.p,a.slot,b.slot):0,aPlayer:a.p,bPlayer:b.p}}),links=pairResults.length?pairResults.reduce((a,x)=>a+x.score,0)/pairResults.length:0;const groups=['GK','DEF','MID','FWD'],lineScores=groups.map(g=>{const line=selected.filter(x=>slotGroup(x.slot.label)===g);return line.length?line.reduce((a,x)=>a+(x.p?positionalQuality(x.p,x.slot.label)*positionFit(x.p,x.slot.label)/100:0),0)/line.length:0}),avg=lineScores.reduce((a,n)=>a+n,0)/lineScores.length,spread=Math.max(...lineScores)-Math.min(...lineScores),balance=Math.max(0,avg-spread*.22);let raw=position*.38+tactics*.21+links*.18+quality*.13+balance*.10;if(count===11)raw*=1.055;if(count===11&&position>=96&&links>=88)raw+=2;const score=scoreClamp(raw),rank=chemistryRank(score,count),worst=selected.filter(x=>x.p).map(x=>({...x,fit:positionFit(x.p,x.slot.label)})).sort((a,b)=>a.fit-b.fit)[0],strong=pairResults.filter(x=>x.score).sort((a,b)=>b.score-a.score)[0];return{score,rank,count,position:scoreClamp(position),tactics:scoreClamp(tactics),links:scoreClamp(links),quality:scoreClamp(quality),balance:scoreClamp(balance),pairs:pairResults,worst,strong}}
function renderChemistry(){const c=computeChemistry(),panel=$('#chemistryPanel');if(!panel)return;const tier=c.score>=97?'ultimate':c.score>=88?'super':c.score>=76?'strong':c.score>=62?'connected':c.score>=45?'building':'weak';panel.dataset.tier=c.count?tier:'empty';$('#chemistryScore').textContent=c.score;$('#connectionRank').textContent=c.rank;$('#connectionCount').textContent=`${c.count} of 11 selected`;$('#connectionFill').style.width=`${c.score}%`;$('#tacticDescription').textContent=TACTICS[state.tactic].description;const parts=[['POSITION FIT',c.position],['TACTICAL FIT',c.tactics],['PARTNERSHIPS',c.links],['ROLE QUALITY',c.quality],['TEAM BALANCE',c.balance]];$('#chemistryBreakdown').innerHTML=parts.map(([l,v])=>`<div><span>${l}</span><i><b style="width:${v}%"></b></i><em>${v}</em></div>`).join('');const notes=[];if(c.count<11)notes.push(`<p><b>＋ ${11-c.count}</b> more starter${11-c.count===1?'':'s'} needed to complete the challenge.</p>`);if(c.worst&&c.worst.fit<72)notes.push(`<p class="warning"><b>${esc(c.worst.p.name)}</b> is only ${c.worst.fit}% suited to ${esc(c.worst.slot.label)}.</p>`);else if(c.count)notes.push('<p><b>✓ Natural roles:</b> the selected players are positionally well placed.</p>');if(c.strong)notes.push(`<p><b>Strongest link:</b> ${esc(c.strong.aPlayer.name)} + ${esc(c.strong.bPlayer.name)} (${c.strong.score}).</p>`);if(c.score===100)notes.unshift('<p class="ultimate"><b>★ Ultimate Leeds XI unlocked.</b> Save it and challenge other Leeds fans.</p>');$('#connectionInsights').innerHTML=notes.join('')}
function renderConnectionLines(){const svg=$('#connectionLines');if(!svg)return;const c=computeChemistry();svg.innerHTML=c.pairs.map(link=>{const a=state.slots[link.a],b=state.slots[link.b],filled=link.aPlayer&&link.bPlayer,tier=!filled?'empty':link.score>=88?'elite':link.score>=74?'strong':link.score>=56?'medium':'weak';return `<line x1="${a.x}" y1="${a.y}" x2="${b.x}" y2="${b.y}" class="link-${tier}" vector-effect="non-scaling-stroke"><title>${filled?`${link.aPlayer.name} + ${link.bPlayer.name}: ${link.score}`:'Unfilled connection'}</title></line>`}).join('')}

function render(){state.title=$('#xiTitle')?.value||state.title;$('#pitchTitle').textContent=state.title.toUpperCase();$('#pitchFormation').textContent=state.formation;$('#heroFormation').textContent=state.formation;$('#heroSelected').textContent=`${state.slots.filter(s=>s.slug).length}/11`;const holder=$('#pitchSlots');holder.innerHTML=state.slots.map((slot,i)=>{const p=bySlug.get(slot.slug),cap=slot.slug&&state.captain===slot.slug?'C':slot.slug&&state.viceCaptain===slot.slug?'V':'',fit=p?positionFit(p,slot.label):0,tier=fitTier(fit);return `<div class="pitch-slot ${slot.label==='GK'?'gk':''} ${p?'filled':'empty'} ${p?'fit-'+tier:''}" data-slot="${i}" style="left:${slot.x}%;top:${slot.y}%" title="${p?`${esc(p.name)} — ${fit}% position fit`:'Choose a player'}"><button class="remove-slot" data-remove="${i}" title="Remove player">×</button>${cap?`<i class="${cap==='C'?'captain':'vice'}-badge">${cap}</i>`:''}<div class="shirt-marker"><b>${p?(p.shirtNumber||initials(p.name)): '+'}</b></div><span class="slot-label">${esc(p?.name||'Choose player')}</span><span class="slot-role">${esc(slot.label)}</span>${p?`<span class="slot-fit">${fit} FIT</span>`:''}</div>`}).join('');bindSlots();renderLeadership();renderBench();renderSquadProfile();renderChemistry();renderConnectionLines();saveDraft();}
function bindSlots(){ $$('.pitch-slot').forEach(el=>{let moved=false,startX=0,startY=0,startLeft=0,startTop=0;const index=Number(el.dataset.slot);el.addEventListener('pointerdown',e=>{if(e.target.closest('.remove-slot'))return;moved=false;startX=e.clientX;startY=e.clientY;startLeft=state.slots[index].x;startTop=state.slots[index].y;el.setPointerCapture(e.pointerId);el.classList.add('dragging')});el.addEventListener('pointermove',e=>{if(!el.hasPointerCapture(e.pointerId))return;const pitch=$('#footballPitch').getBoundingClientRect(),dx=(e.clientX-startX)/pitch.width*100,dy=(e.clientY-startY)/pitch.height*100;if(Math.abs(dx)+Math.abs(dy)>.8)moved=true;state.slots[index].x=Math.max(5,Math.min(95,startLeft+dx));state.slots[index].y=Math.max(5,Math.min(95,startTop+dy));el.style.left=state.slots[index].x+'%';el.style.top=state.slots[index].y+'%'});el.addEventListener('pointerup',e=>{el.classList.remove('dragging');try{el.releasePointerCapture(e.pointerId)}catch{}if(!moved)openPicker({type:'slot',index,group:slotGroup(state.slots[index].label),label:state.slots[index].label});saveDraft()})});$$('[data-remove]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();const i=Number(b.dataset.remove),old=state.slots[i].slug;state.slots[i].slug='';if(state.captain===old)state.captain='';if(state.viceCaptain===old)state.viceCaptain='';render()}));}
function renderLeadership(){const chosen=state.slots.map(s=>bySlug.get(s.slug)).filter(Boolean),opts='<option value="">Choose player</option>'+chosen.map(p=>`<option value="${p.slug}">${esc(p.name)}</option>`).join('');$('#captainSelect').innerHTML=opts;$('#viceCaptainSelect').innerHTML=opts;$('#captainSelect').value=state.captain;$('#viceCaptainSelect').value=state.viceCaptain}
function renderBench(){const h=$('#xiBench');h.innerHTML=state.subs.length?state.subs.map((slug,i)=>{const p=bySlug.get(slug);return `<div class="bench-player"><span>${initials(p?.name)}</span><div><b>${esc(p?.name||slug)}</b><small>${p?.role||'ARCHIVE'} • ${p?.rating?.overall||'—'} rating</small></div><button data-remove-sub="${i}">×</button></div>`}).join(''):'<p>No substitutes selected.</p>';$$('[data-remove-sub]').forEach(b=>b.addEventListener('click',()=>{state.subs.splice(Number(b.dataset.removeSub),1);render()}))}
function renderSquadProfile(){const rs=state.slots.map(s=>bySlug.get(s.slug)?.rating).filter(Boolean),score=rs.length?Math.round(rs.reduce((a,r)=>a+r.overall,0)/rs.length):0;$('#squadRating').textContent=score||'—';const labels=['ATTACK','CREATION','CONTROL','DEFENCE','PHYSICAL','IMPACT'];const vals=labels.map((_,i)=>rs.length?Math.round(rs.reduce((a,r)=>a+(r.scores[i]||0),0)/rs.length):0);$('#squadBars').innerHTML=labels.map((l,i)=>`<div class="squad-bar"><span>${l}</span><i style="--value:${vals[i]}%"></i><b>${vals[i]||'—'}</b></div>`).join('')}
function openPicker(target){pickerTarget=target;$('#playerPicker').classList.add('open');$('#playerPicker').setAttribute('aria-hidden','false');$('#pickerSlotLabel').textContent=target.type==='sub'?'ADD SUBSTITUTE':`${target.label} POSITION`;$('#playerSearch').value='';$('#pickerRole').value=target.group||'all';renderPicker();setTimeout(()=>$('#playerSearch').focus(),60)}
function closePicker(){$('#playerPicker').classList.remove('open');$('#playerPicker').setAttribute('aria-hidden','true');pickerTarget=null}
function filteredPicker(){const q=$('#playerSearch').value.trim().toLowerCase(),role=$('#pickerRole').value,era=$('#pickerEra').value,used=new Set([...state.slots.map(s=>s.slug),...state.subs]);const list=players.filter(p=>(!q||`${p.name} ${p.position} ${p.nationality}`.toLowerCase().includes(q))&&(role==='all'||p.group===role)&&(era==='all'||(era==='current')===!!p.isCurrent)&&(!used.has(p.slug)||pickerTarget?.type==='slot'&&state.slots[pickerTarget.index]?.slug===p.slug));if(pickerTarget?.type==='slot'){const label=state.slots[pickerTarget.index]?.label||pickerTarget.label;list.sort((a,b)=>candidateFit(b,label)-candidateFit(a,label)||(b.rating.overall-a.rating.overall));}return list.slice(0,160)}
function renderPicker(){const list=filteredPicker(),label=pickerTarget?.type==='slot'?(state.slots[pickerTarget.index]?.label||pickerTarget.label):'';$('#playerPickerList').innerHTML=list.length?list.map(p=>{const fit=label?positionFit(p,label):null;return `<button class="picker-player ${previewSlug===p.slug?'focused':''}" data-pick="${p.slug}" type="button"><span class="picker-avatar">${initials(p.name)}</span><span><b>${esc(p.name)}</b><small>${p.role} • ${p.appearances??'—'} apps${p.isCurrent?' • CURRENT':''}</small></span><span class="picker-metrics"><em>${p.rating.overall}</em>${fit!==null?`<i class="fit-${fitTier(fit)}">${fit} FIT</i>`:''}</span></button>`}).join(''):'<div class="preview-empty"><strong>No player matched.</strong><small>Change the role filter or search.</small></div>';$$('[data-pick]').forEach(b=>{b.addEventListener('mouseenter',()=>preview(b.dataset.pick));b.addEventListener('focus',()=>preview(b.dataset.pick));b.addEventListener('click',()=>assign(b.dataset.pick))});if(list[0])preview(previewSlug&&list.some(p=>p.slug===previewSlug)?previewSlug:list[0].slug)}
function assign(slug){if(!pickerTarget)return;if(pickerTarget.type==='slot')state.slots[pickerTarget.index].slug=slug;else if(pickerTarget.type==='sub'&&!state.subs.includes(slug)&&state.subs.length<9)state.subs.push(slug);closePicker();render();toast(`${bySlug.get(slug)?.name||'Player'} added to your XI`)}
function radarSvg(p){const r=p.rating,labels=r.labels,vals=r.scores,c=145,rad=105,pt=(i,v)=>{const a=-Math.PI/2+Math.PI*2*i/6,s=v/100;return`${(c+Math.cos(a)*rad*s).toFixed(1)},${(c+Math.sin(a)*rad*s).toFixed(1)}`},ring=n=>labels.map((_,i)=>pt(i,n)).join(' ');return `<svg viewBox="0 0 290 290" role="img" aria-label="${esc(p.name)} White DNA chart"><defs><linearGradient id="radarFill" x1="0" x2="1"><stop stop-color="#0b83ff" stop-opacity=".64"/><stop offset="1" stop-color="#55d4ff" stop-opacity=".3"/></linearGradient></defs>${[20,40,60,80,100].map(n=>`<polygon points="${ring(n)}" fill="none" stroke="rgba(104,194,255,.2)"/>`).join('')}${labels.map((_,i)=>`<line x1="${c}" y1="${c}" x2="${pt(i,100).split(',')[0]}" y2="${pt(i,100).split(',')[1]}" stroke="rgba(104,194,255,.18)"/>`).join('')}<polygon points="${labels.map((_,i)=>pt(i,vals[i])).join(' ')}" fill="url(#radarFill)" stroke="#59d4ff" stroke-width="2"/>${labels.map((l,i)=>{const a=-Math.PI/2+Math.PI*2*i/6,x=c+Math.cos(a)*132,y=c+Math.sin(a)*132;return`<text x="${x}" y="${y}" text-anchor="middle" dominant-baseline="middle" fill="#bcd8f8" font-size="8" font-weight="800">${l}</text>`}).join('')}</svg>`}
function preview(slug){const p=bySlug.get(slug);if(!p)return;previewSlug=slug;const label=pickerTarget?.type==='slot'?(state.slots[pickerTarget.index]?.label||pickerTarget.label):'',posFit=label?positionFit(p,label):null,tacFit=tacticalFit(p,state.tactic);$('#pickerPreview').innerHTML=`<div class="preview-head"><span class="picker-avatar">${initials(p.name)}</span><div><h3>${esc(p.name)}</h3><p>${esc(p.position||p.role)}${p.nationality?' • '+esc(p.nationality):''}</p></div><div class="preview-rating"><strong>${p.rating.overall}</strong><span>WHITE RATING</span></div></div>${label?`<div class="preview-fit-grid"><div class="fit-${fitTier(posFit)}"><span>${esc(label)} POSITION FIT</span><b>${posFit}</b></div><div><span>${esc(TACTICS[state.tactic].name.toUpperCase())} TACTICAL FIT</span><b>${tacFit}</b></div></div>`:''}<div class="mini-radar">${radarSvg(p)}</div><div class="preview-record"><div><span>APPEARANCES</span><b>${p.appearances??'—'}</b></div><div><span>GOALS</span><b>${p.goals??'—'}</b></div><div><span>LEEDS UNITED IMPACT</span><b>${p.rating.impact}</b></div><div><span>ERA</span><b>${p.isCurrent?'CURRENT':'ARCHIVE'}</b></div></div><p class="preview-note">${posFit!==null&&posFit<45?`This is a severe out-of-position selection and will sharply reduce team connection. `:''}${esc(p.rating.note)}</p>`;$$('[data-pick]').forEach(b=>b.classList.toggle('focused',b.dataset.pick===slug))}
function cleanState(input){const f=FORMATIONS[input?.formation]?input.formation:'4-3-3',base=FORMATIONS[f],t=TACTICS[input?.tactic]?input.tactic:'balanced';return{title:String(input?.title||'My Ultimate Leeds XI').slice(0,80),formation:f,tactic:t,slots:base.map((s,i)=>({id:`slot-${i}`,label:s[0],x:Number(input?.slots?.[i]?.x)||s[1],y:Number(input?.slots?.[i]?.y)||s[2],slug:bySlug.has(input?.slots?.[i]?.slug)?input.slots[i].slug:''})),subs:(input?.subs||[]).filter(s=>bySlug.has(s)).slice(0,9),captain:bySlug.has(input?.captain)?input.captain:'',viceCaptain:bySlug.has(input?.viceCaptain)?input.viceCaptain:'',updatedAt:input?.updatedAt||new Date().toISOString()}}
function payload(){return{...state,title:$('#xiTitle').value.trim()||'My Ultimate Leeds XI',updatedAt:new Date().toISOString()}}
function saveDraft(){try{localStorage.setItem(DRAFT,JSON.stringify(payload()))}catch{}}
function localSaves(){try{return JSON.parse(localStorage.getItem(STORE)||'[]')}catch{return[]}}
function writeLocalSaves(v){localStorage.setItem(STORE,JSON.stringify(v.slice(0,30)))}
async function saveXi(){state=cleanState(payload());const saves=localSaves(),id=`local-${Date.now()}`;saves.unshift({id,title:state.title,formation:state.formation,payload:state,updatedAt:state.updatedAt});writeLocalSaves(saves);if(member){try{await fetch('/api/member/xis',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(state)})}catch{}}renderSaved();toast(member?'Saved to My Leeds':'Saved on this device')}
async function renderSaved(){let saves=localSaves();if(member){try{const r=await fetch('/api/member/xis');if(r.ok){const d=await r.json();saves=[...(d.xis||[]).map(x=>({id:x.id,title:x.title,formation:x.formation,payload:x.payload,remote:true})),...saves]}}catch{}}const seen=new Set();saves=saves.filter(x=>{const k=x.id||x.title+JSON.stringify(x.payload);if(seen.has(k))return false;seen.add(k);return true}).slice(0,20);$('#savedXis').innerHTML=saves.length?saves.map((x,i)=>`<div class="saved-xi"><div><b>${esc(x.title)}</b><small>${esc(x.formation)} • ${x.payload?.slots?.filter(s=>s.slug).length||0}/11</small></div><div class="saved-xi-actions"><button data-load-save="${i}">OPEN</button>${!x.remote?`<button data-delete-save="${x.id}">×</button>`:''}</div></div>`).join(''):'<p>Your saved teams will appear here.</p>';$$('[data-load-save]').forEach(b=>b.addEventListener('click',()=>{state=cleanState(saves[Number(b.dataset.loadSave)].payload);syncInputs();render();toast('XI loaded')}));$$('[data-delete-save]').forEach(b=>b.addEventListener('click',()=>{writeLocalSaves(localSaves().filter(x=>x.id!==b.dataset.deleteSave));renderSaved()}))}
function b64encode(obj){const bytes=new TextEncoder().encode(JSON.stringify(obj));let s='';bytes.forEach(b=>s+=String.fromCharCode(b));return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
function b64decode(s){s=s.replace(/-/g,'+').replace(/_/g,'/');while(s.length%4)s+='=';const bin=atob(s),bytes=Uint8Array.from(bin,c=>c.charCodeAt(0));return JSON.parse(new TextDecoder().decode(bytes))}
async function shareXi(){const data=payload();let url='';try{const r=await fetch('/api/xis/share',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(data)});if(r.ok){const d=await r.json();url=new URL(d.url||`/build-your-xi?xi=${d.shareId}`,location.origin).href}}catch{}if(!url)url=new URL(`build-your-xi.html?lineup=${b64encode(data)}`,location.href).href;try{await navigator.clipboard.writeText(url);toast('Share link copied')}catch{prompt('Copy your XI link',url)}}
function exportImage(){const data=payload(),chem=computeChemistry(),canvas=document.createElement('canvas');canvas.width=1200;canvas.height=1500;const c=canvas.getContext('2d');const grad=c.createLinearGradient(0,0,1200,1500);grad.addColorStop(0,'#071f4d');grad.addColorStop(1,'#020916');c.fillStyle=grad;c.fillRect(0,0,1200,1500);c.fillStyle='#ffcd00';c.font='800 28px Inter';c.fillText('LEEDSBUZZ.BIZ  •  ULTIMATE XI CHALLENGE',70,78);c.fillStyle='#fff';c.font='900 57px Inter';c.fillText(data.title.toUpperCase().slice(0,32),70,145);c.fillStyle='#c7d1de';c.font='700 23px Inter';c.fillText(`${data.formation}  •  ${TACTICS[data.tactic].name.toUpperCase()}  •  CONNECTION ${chem.score}/100`,72,188);c.fillStyle='rgba(255,255,255,.13)';c.fillRect(72,207,1056,12);const m=c.createLinearGradient(72,0,1128,0);m.addColorStop(0,'#ffcd00');m.addColorStop(1,'#fff1a6');c.fillStyle=m;c.fillRect(72,207,1056*chem.score/100,12);const px=145,py=245,pw=910,ph=1120;c.fillStyle='#08734b';c.fillRect(px,py,pw,ph);for(let i=0;i<10;i++){c.fillStyle=i%2?'rgba(255,255,255,.02)':'rgba(0,0,0,.025)';c.fillRect(px,py+i*ph/10,pw,ph/10)}c.strokeStyle='rgba(255,255,255,.72)';c.lineWidth=4;c.strokeRect(px+18,py+18,pw-36,ph-36);c.beginPath();c.moveTo(px+18,py+ph/2);c.lineTo(px+pw-18,py+ph/2);c.stroke();c.beginPath();c.arc(px+pw/2,py+ph/2,105,0,Math.PI*2);c.stroke();data.slots.forEach(slot=>{const p=bySlug.get(slot.slug),x=px+pw*slot.x/100,y=py+ph*slot.y/100;c.beginPath();c.fillStyle=slot.label==='GK'?'#ffb52e':'#ffcd00';c.strokeStyle=p&&positionFit(p,slot.label)<45?'#ff5f72':'#ffffff';c.lineWidth=5;c.arc(x,y,43,0,Math.PI*2);c.fill();c.stroke();c.fillStyle='#fff';c.textAlign='center';c.font='900 22px Inter';c.fillText(p?initials(p.name):slot.label,x,y+7);c.font='800 17px Inter';c.fillText((p?.name||'EMPTY').toUpperCase().slice(0,18),x,y+70);if(p){c.font='800 13px Inter';c.fillStyle=positionFit(p,slot.label)<45?'#ff9cab':'#bcecff';c.fillText(`${positionFit(p,slot.label)} FIT`,x,y+91)}if(data.captain===slot.slug||data.viceCaptain===slot.slug){c.fillStyle='#ffbf47';c.beginPath();c.arc(x+38,y-38,18,0,Math.PI*2);c.fill();c.fillStyle='#07101d';c.font='900 17px Inter';c.fillText(data.captain===slot.slug?'C':'V',x+38,y-32)}});c.textAlign='left';c.fillStyle='#fff';c.font='700 18px Inter';c.fillText(`${chem.rank} • Made by a Leeds fan on LeedsBuzz.biz`,70,1445);canvas.toBlob(blob=>{const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${slugify(data.title)||'leeds-xi'}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)},'image/png')}
function syncInputs(){$('#xiTitle').value=state.title;$('#formationSelect').value=state.formation;$('#tacticSelect').value=state.tactic}
async function loadShared(){const u=new URL(location.href),id=u.searchParams.get('xi'),encoded=u.searchParams.get('lineup');try{if(id){const r=await fetch(`/api/xis/share/${encodeURIComponent(id)}`);if(r.ok){const d=await r.json();state=cleanState(d.xi?.payload||d.payload);toast('Shared Leeds XI loaded');return true}}if(encoded){state=cleanState(b64decode(encoded));toast('Shared Leeds XI loaded');return true}}catch(e){console.warn(e)}return false}
async function loadMemberSavedFromQuery(){const u=new URL(location.href),id=u.searchParams.get('saved');if(!id||!member)return false;try{const r=await fetch('/api/member/xis',{cache:'no-store'});if(!r.ok)return false;const d=await r.json(),found=(d.xis||[]).find(x=>x.id===id);if(!found)return false;state=cleanState(found.payload);u.searchParams.delete('saved');history.replaceState({},'',u);toast('Saved Leeds XI loaded');return true}catch{return false}}
async function memberStatus(){try{const r=await fetch('/api/member/me');if(r.ok){const d=await r.json();member=d.authenticated?d.member:null;const chip=$('.profile-chip span');if(chip&&member)chip.textContent=member.displayName||'My Leeds'}}catch{}}
function addQueuedPlayer(){const u=new URL(location.href);let queued='';try{queued=sessionStorage.getItem('leedsBuzzXIAddPlayer')||'';sessionStorage.removeItem('leedsBuzzXIAddPlayer')}catch{}const slug=u.searchParams.get('add')||queued;if(!bySlug.has(slug))return;const p=bySlug.get(slug),preferred=p.group,slot=state.slots.find(s=>!s.slug&&slotGroup(s.label)===preferred)||state.slots.find(s=>!s.slug);if(slot){slot.slug=slug;toast(`${p.name} added from the White Vault`)}u.searchParams.delete('add');history.replaceState({},'',u)}
function bind(){Object.keys(FORMATIONS).forEach(f=>$('#formationSelect').insertAdjacentHTML('beforeend',`<option>${f}</option>`));Object.entries(TACTICS).forEach(([key,t])=>$('#tacticSelect').insertAdjacentHTML('beforeend',`<option value="${key}">${t.name}</option>`));$('#formationSelect').addEventListener('change',e=>{const old=state.slots.slice();state.formation=e.target.value;state.slots=FORMATIONS[state.formation].map((s,i)=>({id:`slot-${i}`,label:s[0],x:s[1],y:s[2],slug:old[i]?.slug||''}));render()});$('#tacticSelect').addEventListener('change',e=>{state.tactic=e.target.value;render();toast(`${TACTICS[state.tactic].name} tactic selected`)});$('#xiTitle').addEventListener('input',()=>{state.title=$('#xiTitle').value;render()});$('#captainSelect').addEventListener('change',e=>{state.captain=e.target.value;if(state.viceCaptain===state.captain)state.viceCaptain='';render()});$('#viceCaptainSelect').addEventListener('change',e=>{state.viceCaptain=e.target.value;if(state.captain===state.viceCaptain)state.captain='';render()});$('#addSubBtn').addEventListener('click',()=>openPicker({type:'sub',group:'all'}));$$('[data-close-picker]').forEach(x=>x.addEventListener('click',closePicker));$('#playerSearch').addEventListener('input',renderPicker);$('#pickerRole').addEventListener('change',renderPicker);$('#pickerEra').addEventListener('change',renderPicker);document.addEventListener('keydown',e=>{if(e.key==='Escape')closePicker()});$('#newXiBtn').addEventListener('click',()=>{if(confirm('Start a new XI?')){newState($('#formationSelect').value,[],state.tactic);syncInputs();render()}});$('#saveXiBtn').addEventListener('click',saveXi);$('#shareXiBtn').addEventListener('click',shareXi);$('#exportXiBtn').addEventListener('click',exportImage);$('#refreshSavesBtn').addEventListener('click',renderSaved)}
async function start(){buildPlayers();newState();bind();await memberStatus();const saved=await loadMemberSavedFromQuery();const shared=saved?false:await loadShared();if(!saved&&!shared){try{const d=JSON.parse(localStorage.getItem(DRAFT)||localStorage.getItem(OLD_DRAFT)||'null');if(d)state=cleanState(d)}catch{}}addQueuedPlayer();syncInputs();render();renderSaved()}
start();
