(() => {
  if (window.__leedsGlobalSearch) return; window.__leedsGlobalSearch=true;
  const html=`<button class="cb-search-launch" type="button" aria-label="Search LeedsBuzz.biz">⌕</button><div class="cb-search-layer" aria-hidden="true"><div class="cb-search-backdrop" data-search-close></div><section class="cb-search-dialog" role="dialog" aria-modal="true" aria-labelledby="cbSearchTitle"><header class="cb-search-head"><div><span>SEARCH THE WHOLE LEEDS UNITED ARCHIVE</span><h2 id="cbSearchTitle">Find players, managers, matches and records.</h2></div><button class="cb-search-close" type="button" data-search-close aria-label="Close">×</button></header><form class="cb-search-form"><input type="search" name="q" maxlength="120" autocomplete="off" placeholder="Search Billy Bremner, Wembley 1972, Don Revie…"><button type="submit">SEARCH</button></form><div class="cb-search-hint">White Vault players open in their full profile. History facts, records and matches open in the History archive.</div><div class="cb-search-results"></div></section></div>`;
  document.body.insertAdjacentHTML('beforeend',html);
  const layer=document.querySelector('.cb-search-layer'),input=layer.querySelector('input'),results=layer.querySelector('.cb-search-results');
  document.querySelector('.cb-search-launch').addEventListener('click',open);layer.querySelectorAll('[data-search-close]').forEach(el=>el.addEventListener('click',close));
  layer.querySelector('form').addEventListener('submit',async event=>{event.preventDefault();const q=input.value.trim();if(!q)return;results.innerHTML='<div class="cb-search-empty">Searching the White Archive…</div>';try{const response=await fetch(`/api/bizbot/search?q=${encodeURIComponent(q)}`,{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error||'Search failed');render(data.results||[])}catch(error){results.innerHTML=`<div class="cb-search-empty">${escapeHtml(error.message||'Search unavailable')}</div>`}});
  document.addEventListener('keydown',event=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();open()}else if(event.key==='Escape')close()});
  function open(){layer.classList.add('open');layer.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';setTimeout(()=>input.focus(),20)}
  function close(){layer.classList.remove('open');layer.setAttribute('aria-hidden','true');document.body.style.overflow=''}
  function render(rows){if(!rows.length){results.innerHTML='<div class="cb-search-empty">No matching verified archive entry was found.</div>';return}results.innerHTML=rows.slice(0,20).map(row=>{const type=String(row.type||'fact');const title=row.full_name||row.title||matchTitle(row)||'Leeds United archive result';const detail=row.body||row.value_text||row.notes||row.reason||row.competition_name||'';const href=resultHref(row);return `<a class="cb-search-result" href="${href}"><span class="cb-search-type">${escapeHtml(type.toUpperCase())}</span><span><b>${escapeHtml(title)}</b><small>${escapeHtml(trim(detail,150))}</small></span><span>→</span></a>`}).join('')}
  function resultHref(row){if(row.type==='player'&&row.slug)return `/white-vault?player=${encodeURIComponent(row.slug)}`;if(row.type==='manager')return `/history#seasonArchive`;if(row.type==='match')return `/history#seasonArchive`;return `/history#recordRoom`}
  function matchTitle(row){if(row.home_team||row.away_team)return `${row.home_team||''} v ${row.away_team||''}`;return''}
  function trim(value,max){const text=String(value||'').replace(/\s+/g,' ').trim();return text.length>max?`${text.slice(0,max-1)}…`:text}
  function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
})();
